var pokemon = [
        {
            name: "ekans"               
        }, {
            name: "wartortle"               
        }, {
            name: "blastoise"               
        }, {
            name: "metapod"               
        }, {
            name: "butterfree"               
        }, {
            name: "weedle"               
        }, {
            name: "kakuna"               
        }, {
            name: "beedrill"               
        }, {
            name: "arbok"               
        }, {
            name: "pidgeotto"               
        }, {
            name: "pidgeot"               
        }, {
            name: "raticate"               
        }, {
            name: "spearow"               
        }, {
            name: "fearow"               
        }, {
            name: "raichu"               
        }, {
            name: "pikachu"               
        }, {
            name: "nidoran-f"               
        }, {
            name: "sandshrew"               
        }, {
            name: "nidorina"               
        }, {
            name: "nidoran-m"               
        }, {
            name: "nidoking"               
        }, {
            name: "nidoqueen"               
        }, {
            name: "vulpix"               
        }, {
            name: "nidorino"               
        }, {
            name: "clefable"               
        }, {
            name: "ninetales"               
        }, {
            name: "jigglypuff"               
        }, {
            name: "venomoth"               
        }, {
            name: "golbat"               
        }, {
            name: "wigglytuff"               
        }, {
            name: "zubat"               
        }, {
            name: "oddish"               
        }, {
            name: "gloom"               
        }, {
            name: "meowth"               
        }, {
            name: "mankey"               
        }, {
            name: "vileplume"               
        }, {
            name: "paras"               
        }, {
            name: "parasect"               
        }, {
            name: "venonat"               
        }, {
            name: "diglett"               
        }, {
            name: "dugtrio"               
        }, {
            name: "persian"               
        }, {
            name: "psyduck"               
        }, {
            name: "golduck"               
        }, {
            name: "growlithe"               
        }, {
            name: "arcanine"               
        }, {
            name: "poliwag"               
        }, {
            name: "poliwhirl"               
        }, {
            name: "poliwrath"               
        }, {
            name: "abra"               
        }, {
            name: "kadabra"               
        }, {
            name: "machop"               
        }, {
            name: "machoke"               
        }, {
            name: "machamp"               
        }, {
            name: "bellsprout"               
        }, {
            name: "ivysaur"               
        }, {
            name: "charmander"               
        }, {
            name: "venusaur"               
        }, {
            name: "rattata"               
        }, {
            name: "charmeleon"               
        }, {
            name: "squirtle"               
        }, {
            name: "caterpie"               
        }, {
            name: "pidgey"               
        }, {
            name: "slowbro"               
        }, {
            name: "rapidash"               
        }, {
            name: "magnemite"               
        }, {
            name: "magneton"               
        }, {
            name: "farfetchd"               
        }, {
            name: "doduo"               
        }, {
            name: "haunter"               
        }, {
            name: "dewgong"               
        }, {
            name: "dodrio"               
        }, {
            name: "seel"               
        }, {
            name: "grimer"               
        }, {
            name: "cloyster"               
        }, {
            name: "muk"               
        }, {
            name: "gastly"               
        }, {
            name: "drowzee"               
        }, {
            name: "onix"               
        }, {
            name: "gengar"               
        }, {
            name: "exeggcute"               
        }, {
            name: "hypno"               
        }, {
            name: "krabby"               
        }, {
            name: "kingler"               
        }, {
            name: "voltorb"               
        }, {
            name: "electrode"               
        }, {
            name: "exeggutor"               
        }, {
            name: "cubone"               
        }, {
            name: "lickitung"               
        }, {
            name: "hitmonlee"               
        }, {
            name: "hitmonchan"               
        }, {
            name: "weezing"               
        }, {
            name: "koffing"               
        }, {
            name: "rhydon"               
        }, {
            name: "rhyhorn"               
        }, {
            name: "chansey"               
        }, {
            name: "tangela"               
        }, {
            name: "kangaskhan"               
        }, {
            name: "horsea"               
        }, {
            name: "seadra"               
        }, {
            name: "staryu"               
        }, {
            name: "starmie"               
        }, {
            name: "goldeen"               
        }, {
            name: "mr-mime"               
        }, {
            name: "scyther"               
        }, {
            name: "jynx"               
        }, {
            name: "magmar"               
        }, {
            name: "electabuzz"               
        }, {
            name: "pinsir"               
        }, {
            name: "ditto"               
        }, {
            name: "lapras"               
        }, {
            name: "tauros"               
        }, {
            name: "gyarados"               
        }, {
            name: "vaporeon"               
        }, {
            name: "eevee"               
        }, {
            name: "flareon"               
        }, {
            name: "jolteon"               
        }, {
            name: "porygon"               
        }, {
            name: "omanyte"               
        }, {
            name: "victreebel"               
        }, {
            name: "tentacool"               
        }, {
            name: "tentacruel"               
        }, {
            name: "graveler"               
        }, {
            name: "geodude"               
        }, {
            name: "golem"               
        }, {
            name: "ponyta"               
        }, {
            name: "meganium"               
        }, {
            name: "dratini"               
        }, {
            name: "bayleef"               
        }, {
            name: "mewtwo"               
        }, {
            name: "sentret"               
        }, {
            name: "mew"               
        }, {
            name: "chikorita"               
        }, {
            name: "quilava"               
        }, {
            name: "noctowl"               
        }, {
            name: "cyndaquil"               
        }, {
            name: "typhlosion"               
        }, {
            name: "natu"               
        }, {
            name: "totodile"               
        }, {
            name: "croconaw"               
        }, {
            name: "feraligatr"               
        }, {
            name: "furret"               
        }, {
            name: "hoothoot"               
        }, {
            name: "crobat"               
        }, {
            name: "ledyba"               
        }, {
            name: "ledian"               
        }, {
            name: "ariados"               
        }, {
            name: "chinchou"               
        }, {
            name: "lanturn"               
        }, {
            name: "cleffa"               
        }, {
            name: "pichu"               
        }, {
            name: "igglybuff"               
        }, {
            name: "togetic"               
        }, {
            name: "togepi"               
        }, {
            name: "xatu"               
        }, {
            name: "mareep"               
        }, {
            name: "ampharos"               
        }, {
            name: "bellossom"               
        }, {
            name: "politoed"               
        }, {
            name: "marill"               
        }, {
            name: "sudowoodo"               
        }, {
            name: "azumarill"               
        }, {
            name: "hoppip"               
        }, {
            name: "sunkern"               
        }, {
            name: "jumpluff"               
        }, {
            name: "skiploom"               
        }, {
            name: "aipom"               
        }, {
            name: "sunflora"               
        }, {
            name: "yanma"               
        }, {
            name: "espeon"               
        }, {
            name: "umbreon"               
        }, {
            name: "wooper"               
        }, {
            name: "quagsire"               
        }, {
            name: "murkrow"               
        }, {
            name: "misdreavus"               
        }, {
            name: "girafarig"               
        }, {
            name: "unown"               
        }, {
            name: "pineco"               
        }, {
            name: "wobbuffet"               
        }, {
            name: "dunsparce"               
        }, {
            name: "forretress"               
        }, {
            name: "kabuto"               
        }, {
            name: "gligar"               
        }, {
            name: "aerodactyl"               
        }, {
            name: "snorlax"               
        }, {
            name: "articuno"               
        }, {
            name: "zapdos"               
        }, {
            name: "moltres"               
        }, {
            name: "dragonair"               
        }, {
            name: "slugma"               
        }, {
            name: "remoraid"               
        }, {
            name: "magcargo"               
        }, {
            name: "octillery"               
        }, {
            name: "delibird"               
        }, {
            name: "mantine"               
        }, {
            name: "houndoom"               
        }, {
            name: "skarmory"               
        }, {
            name: "houndour"               
        }, {
            name: "kingdra"               
        }, {
            name: "donphan"               
        }, {
            name: "phanpy"               
        }, {
            name: "porygon2"               
        }, {
            name: "smoochum"               
        }, {
            name: "stantler"               
        }, {
            name: "smeargle"               
        }, {
            name: "tyrogue"               
        }, {
            name: "elekid"               
        }, {
            name: "magby"               
        }, {
            name: "miltank"               
        }, {
            name: "entei"               
        }, {
            name: "blissey"               
        }, {
            name: "raikou"               
        }, {
            name: "suicune"               
        }, {
            name: "larvitar"               
        }, {
            name: "pupitar"               
        }, {
            name: "sceptile"               
        }, {
            name: "lugia"               
        }, {
            name: "ho-oh"               
        }, {
            name: "celebi"               
        }, {
            name: "treecko"               
        }, {
            name: "grovyle"               
        }, {
            name: "linoone"               
        }, {
            name: "torchic"               
        }, {
            name: "blaziken"               
        }, {
            name: "combusken"               
        }, {
            name: "wurmple"               
        }, {
            name: "mudkip"               
        }, {
            name: "marshtomp"               
        }, {
            name: "swampert"               
        }, {
            name: "cascoon"               
        }, {
            name: "poochyena"               
        }, {
            name: "mightyena"               
        }, {
            name: "silcoon"               
        }, {
            name: "beautifly"               
        }, {
            name: "dustox"               
        }, {
            name: "seedot"               
        }, {
            name: "lotad"               
        }, {
            name: "lombre"               
        }, {
            name: "ludicolo"               
        }, {
            name: "nuzleaf"               
        }, {
            name: "shiftry"               
        }, {
            name: "taillow"               
        }, {
            name: "scizor"               
        }, {
            name: "granbull"               
        }, {
            name: "heracross"               
        }, {
            name: "qwilfish"               
        }, {
            name: "shuckle"               
        }, {
            name: "sneasel"               
        }, {
            name: "ursaring"               
        }, {
            name: "breloom"               
        }, {
            name: "shroomish"               
        }, {
            name: "vigoroth"               
        }, {
            name: "slakoth"               
        }, {
            name: "loudred"               
        }, {
            name: "nosepass"               
        }, {
            name: "slaking"               
        }, {
            name: "nincada"               
        }, {
            name: "whismur"               
        }, {
            name: "exploud"               
        }, {
            name: "azurill"               
        }, {
            name: "makuhita"               
        }, {
            name: "lairon"               
        }, {
            name: "hariyama"               
        }, {
            name: "mawile"               
        }, {
            name: "skitty"               
        }, {
            name: "delcatty"               
        }, {
            name: "sableye"               
        }, {
            name: "aron"               
        }, {
            name: "aggron"               
        }, {
            name: "electrike"               
        }, {
            name: "medicham"               
        }, {
            name: "roselia"               
        }, {
            name: "minun"               
        }, {
            name: "manectric"               
        }, {
            name: "plusle"               
        }, {
            name: "volbeat"               
        }, {
            name: "illumise"               
        }, {
            name: "swalot"               
        }, {
            name: "gulpin"               
        }, {
            name: "carvanha"               
        }, {
            name: "sharpedo"               
        }, {
            name: "wailmer"               
        }, {
            name: "camerupt"               
        }, {
            name: "torkoal"               
        }, {
            name: "numel"               
        }, {
            name: "spoink"               
        }, {
            name: "trapinch"               
        }, {
            name: "grumpig"               
        }, {
            name: "flygon"               
        }, {
            name: "spinda"               
        }, {
            name: "vibrava"               
        }, {
            name: "cacnea"               
        }, {
            name: "cacturne"               
        }, {
            name: "swablu"               
        }, {
            name: "whiscash"               
        }, {
            name: "lunatone"               
        }, {
            name: "altaria"               
        }, {
            name: "seviper"               
        }, {
            name: "solrock"               
        }, {
            name: "crawdaunt"               
        }, {
            name: "claydol"               
        }, {
            name: "corphish"               
        }, {
            name: "barboach"               
        }, {
            name: "baltoy"               
        }, {
            name: "lileep"               
        }, {
            name: "wingull"               
        }, {
            name: "ralts"               
        }, {
            name: "pelipper"               
        }, {
            name: "masquerain"               
        }, {
            name: "surskit"               
        }, {
            name: "kirlia"               
        }, {
            name: "ninjask"               
        }, {
            name: "absol"               
        }, {
            name: "shuppet"               
        }, {
            name: "wynaut"               
        }, {
            name: "dusclops"               
        }, {
            name: "chimecho"               
        }, {
            name: "snorunt"               
        }, {
            name: "glalie"               
        }, {
            name: "sealeo"               
        }, {
            name: "spheal"               
        }, {
            name: "walrein"               
        }, {
            name: "clamperl"               
        }, {
            name: "huntail"               
        }, {
            name: "gorebyss"               
        }, {
            name: "groudon"               
        }, {
            name: "bagon"               
        }, {
            name: "shelgon"               
        }, {
            name: "relicanth"               
        }, {
            name: "luvdisc"               
        }, {
            name: "metang"               
        }, {
            name: "beldum"               
        }, {
            name: "metagross"               
        }, {
            name: "regirock"               
        }, {
            name: "grotle"               
        }, {
            name: "regice"               
        }, {
            name: "kyogre"               
        }, {
            name: "registeel"               
        }, {
            name: "latias"               
        }, {
            name: "latios"               
        }, {
            name: "rayquaza"               
        }, {
            name: "jirachi"               
        }, {
            name: "turtwig"               
        }, {
            name: "torterra"               
        }, {
            name: "shinx"               
        }, {
            name: "chimchar"               
        }, {
            name: "infernape"               
        }, {
            name: "monferno"               
        }, {
            name: "piplup"               
        }, {
            name: "kricketune"               
        }, {
            name: "roserade"               
        }, {
            name: "prinplup"               
        }, {
            name: "empoleon"               
        }, {
            name: "starly"               
        }, {
            name: "staraptor"               
        }, {
            name: "staravia"               
        }, {
            name: "bidoof"               
        }, {
            name: "kricketot"               
        }, {
            name: "luxio"               
        }, {
            name: "budew"               
        }, {
            name: "luxray"               
        }, {
            name: "cranidos"               
        }, {
            name: "rampardos"               
        }, {
            name: "shieldon"               
        }, {
            name: "feebas"               
        }, {
            name: "bastiodon"               
        }, {
            name: "burmy"               
        }, {
            name: "mothim"               
        }, {
            name: "anorith"               
        }, {
            name: "armaldo"               
        }, {
            name: "kecleon"               
        }, {
            name: "banette"               
        }, {
            name: "milotic"               
        }, {
            name: "castform"               
        }, {
            name: "duskull"               
        }, {
            name: "drifloon"               
        }, {
            name: "chingling"               
        }, {
            name: "lopunny"               
        }, {
            name: "drifblim"               
        }, {
            name: "buneary"               
        }, {
            name: "honchkrow"               
        }, {
            name: "mismagius"               
        }, {
            name: "glameow"               
        }, {
            name: "purugly"               
        }, {
            name: "bronzong"               
        }, {
            name: "stunky"               
        }, {
            name: "skuntank"               
        }, {
            name: "bronzor"               
        }, {
            name: "bonsly"               
        }, {
            name: "mime-jr"               
        }, {
            name: "hippopotas"               
        }, {
            name: "happiny"               
        }, {
            name: "spiritomb"               
        }, {
            name: "gible"               
        }, {
            name: "gabite"               
        }, {
            name: "garchomp"               
        }, {
            name: "munchlax"               
        }, {
            name: "carnivine"               
        }, {
            name: "riolu"               
        }, {
            name: "lucario"               
        }, {
            name: "finneon"               
        }, {
            name: "croagunk"               
        }, {
            name: "hippowdon"               
        }, {
            name: "drapion"               
        }, {
            name: "toxicroak"               
        }, {
            name: "lumineon"               
        }, {
            name: "mantyke"               
        }, {
            name: "snover"               
        }, {
            name: "weavile"               
        }, {
            name: "abomasnow"               
        }, {
            name: "rhyperior"               
        }, {
            name: "magnezone"               
        }, {
            name: "lickilicky"               
        }, {
            name: "yanmega"               
        }, {
            name: "electivire"               
        }, {
            name: "togekiss"               
        }, {
            name: "glaceon"               
        }, {
            name: "magmortar"               
        }, {
            name: "leafeon"               
        }, {
            name: "gliscor"               
        }, {
            name: "mamoswine"               
        }, {
            name: "porygon-z"               
        }, {
            name: "gallade"               
        }, {
            name: "probopass"               
        }, {
            name: "dusknoir"               
        }, {
            name: "froslass"               
        }, {
            name: "rotom"               
        }, {
            name: "uxie"               
        }, {
            name: "mesprit"               
        }, {
            name: "dialga"               
        }, {
            name: "vespiquen"               
        }, {
            name: "buizel"               
        }, {
            name: "pachirisu"               
        }, {
            name: "cherubi"               
        }, {
            name: "floatzel"               
        }, {
            name: "ambipom"               
        }, {
            name: "cherrim"               
        }, {
            name: "gastrodon"               
        }, {
            name: "darkrai"               
        }, {
            name: "tepig"               
        }, {
            name: "snivy"               
        }, {
            name: "servine"               
        }, {
            name: "serperior"               
        }, {
            name: "pignite"               
        }, {
            name: "oshawott"               
        }, {
            name: "emboar"               
        }, {
            name: "stoutland"               
        }, {
            name: "dewott"               
        }, {
            name: "patrat"               
        }, {
            name: "watchog"               
        }, {
            name: "lillipup"               
        }, {
            name: "herdier"               
        }, {
            name: "purrloin"               
        }, {
            name: "liepard"               
        }, {
            name: "pansage"               
        }, {
            name: "simisage"               
        }, {
            name: "pansear"               
        }, {
            name: "tranquill"               
        }, {
            name: "panpour"               
        }, {
            name: "simipour"               
        }, {
            name: "munna"               
        }, {
            name: "musharna"               
        }, {
            name: "pidove"               
        }, {
            name: "woobat"               
        }, {
            name: "unfezant"               
        }, {
            name: "blitzle"               
        }, {
            name: "zebstrika"               
        }, {
            name: "roggenrola"               
        }, {
            name: "boldore"               
        }, {
            name: "gigalith"               
        }, {
            name: "excadrill"               
        }, {
            name: "swoobat"               
        }, {
            name: "drilbur"               
        }, {
            name: "audino"               
        }, {
            name: "timburr"               
        }, {
            name: "conkeldurr"               
        }, {
            name: "tympole"               
        }, {
            name: "palpitoad"               
        }, {
            name: "throh"               
        }, {
            name: "seismitoad"               
        }, {
            name: "sawk"               
        }, {
            name: "sewaddle"               
        }, {
            name: "swadloon"               
        }, {
            name: "venipede"               
        }, {
            name: "whirlipede"               
        }, {
            name: "scolipede"               
        }, {
            name: "cottonee"               
        }, {
            name: "whimsicott"               
        }, {
            name: "petilil"               
        }, {
            name: "regigigas"               
        }, {
            name: "lilligant"               
        }, {
            name: "basculin-red-striped"               
        }, {
            name: "sandile"               
        }, {
            name: "krokorok"               
        }, {
            name: "giratina-altered"               
        }, {
            name: "manaphy"               
        }, {
            name: "victini"               
        }, {
            name: "arceus"               
        }, {
            name: "shaymin-land"               
        }, {
            name: "archeops"               
        }, {
            name: "yamask"               
        }, {
            name: "trubbish"               
        }, {
            name: "cofagrigus"               
        }, {
            name: "tirtouga"               
        }, {
            name: "carracosta"               
        }, {
            name: "archen"               
        }, {
            name: "gothorita"               
        }, {
            name: "zorua"               
        }, {
            name: "gothita"               
        }, {
            name: "zoroark"               
        }, {
            name: "minccino"               
        }, {
            name: "cinccino"               
        }, {
            name: "gothitelle"               
        }, {
            name: "swanna"               
        }, {
            name: "solosis"               
        }, {
            name: "duosion"               
        }, {
            name: "reuniclus"               
        }, {
            name: "vanillite"               
        }, {
            name: "vanillish"               
        }, {
            name: "deerling"               
        }, {
            name: "vanilluxe"               
        }, {
            name: "karrablast"               
        }, {
            name: "sawsbuck"               
        }, {
            name: "emolga"               
        }, {
            name: "escavalier"               
        }, {
            name: "amoonguss"               
        }, {
            name: "frillish"               
        }, {
            name: "foongus"               
        }, {
            name: "jellicent"               
        }, {
            name: "joltik"               
        }, {
            name: "alomomola"               
        }, {
            name: "galvantula"               
        }, {
            name: "klang"               
        }, {
            name: "ferroseed"               
        }, {
            name: "klink"               
        }, {
            name: "ferrothorn"               
        }, {
            name: "tynamo"               
        }, {
            name: "eelektrik"               
        }, {
            name: "beheeyem"               
        }, {
            name: "eelektross"               
        }, {
            name: "litwick"               
        }, {
            name: "elgyem"               
        }, {
            name: "lampent"               
        }, {
            name: "chandelure"               
        }, {
            name: "axew"               
        }, {
            name: "haxorus"               
        }, {
            name: "cubchoo"               
        }, {
            name: "beartic"               
        }, {
            name: "cryogonal"               
        }, {
            name: "shelmet"               
        }, {
            name: "stunfisk"               
        }, {
            name: "accelgor"               
        }, {
            name: "mienfoo"               
        }, {
            name: "mienshao"               
        }, {
            name: "darumaka"               
        }, {
            name: "darmanitan-standard"               
        }, {
            name: "maractus"               
        }, {
            name: "scraggy"               
        }, {
            name: "dwebble"               
        }, {
            name: "scrafty"               
        }, {
            name: "crustle"               
        }, {
            name: "sigilyph"               
        }, {
            name: "vullaby"               
        }, {
            name: "mandibuzz"               
        }, {
            name: "heatmor"               
        }, {
            name: "cobalion"               
        }, {
            name: "deino"               
        }, {
            name: "hydreigon"               
        }, {
            name: "larvesta"               
        }, {
            name: "volcarona"               
        }, {
            name: "delphox"               
        }, {
            name: "thundurus-incarnate"               
        }, {
            name: "terrakion"               
        }, {
            name: "virizion"               
        }, {
            name: "reshiram"               
        }, {
            name: "zekrom"               
        }, {
            name: "landorus-incarnate"               
        }, {
            name: "kyurem"               
        }, {
            name: "keldeo-ordinary"               
        }, {
            name: "genesect"               
        }, {
            name: "meloetta-aria"               
        }, {
            name: "chespin"               
        }, {
            name: "quilladin"               
        }, {
            name: "chesnaught"               
        }, {
            name: "fletchinder"               
        }, {
            name: "fennekin"               
        }, {
            name: "braixen"               
        }, {
            name: "froakie"               
        }, {
            name: "frogadier"               
        }, {
            name: "spewpa"               
        }, {
            name: "greninja"               
        }, {
            name: "bunnelby"               
        }, {
            name: "diggersby"               
        }, {
            name: "fletchling"               
        }, {
            name: "talonflame"               
        }, {
            name: "litleo"               
        }, {
            name: "scatterbug"               
        }, {
            name: "vivillon"               
        }, {
            name: "florges"               
        }, {
            name: "flabebe"               
        }, {
            name: "pancham"               
        }, {
            name: "floette"               
        }, {
            name: "meowstic-male"               
        }, {
            name: "skiddo"               
        }, {
            name: "gogoat"               
        }, {
            name: "furfrou"               
        }, {
            name: "espurr"               
        }, {
            name: "honedge"               
        }, {
            name: "spritzee"               
        }, {
            name: "doublade"               
        }, {
            name: "aegislash"               
        }, {
            name: "swirlix"               
        }, {
            name: "aromatisse"               
        }, {
            name: "bisharp"               
        }, {
            name: "slurpuff"               
        }, {
            name: "malamar"               
        }, {
            name: "inkay"               
        }, {
            name: "binacle"               
        }, {
            name: "golett"               
        }, {
            name: "golurk"               
        }, {
            name: "pawniard"               
        }, {
            name: "bouffalant"               
        }, {
            name: "rufflet"               
        }, {
            name: "braviary"               
        }, {
            name: "durant"               
        }, {
            name: "amaura"               
        }, {
            name: "goomy"               
        }, {
            name: "aurorus"               
        }, {
            name: "klefki"               
        }, {
            name: "sylveon"               
        }, {
            name: "goodra"               
        }, {
            name: "hawlucha"               
        }, {
            name: "dedenne"               
        }, {
            name: "sliggoo"               
        }, {
            name: "gourgeist-average"               
        }, {
            name: "pumpkaboo-average"               
        }, {
            name: "phantump"               
        }, {
            name: "bergmite"               
        }, {
            name: "trevenant"               
        }, {
            name: "zygarde"               
        }, {
            name: "avalugg"               
        }, {
            name: "noibat"               
        }, {
            name: "xerneas"               
        }, {
            name: "noivern"               
        }, {
            name: "yveltal"               
        }, {
            name: "deoxys-attack"               
        }, {
            name: "deoxys-defense"               
        }, {
            name: "skrelp"               
        }, {
            name: "clauncher"               
        }, {
            name: "wormadam-sandy"               
        }, {
            name: "deoxys-speed"               
        }, {
            name: "tyrunt"               
        }, {
            name: "carbink"               
        }, {
            name: "rotom-heat"               
        }, {
            name: "wormadam-trash"               
        }, {
            name: "darmanitan-zen"               
        }, {
            name: "rotom-frost"               
        }, {
            name: "shaymin-sky"               
        }, {
            name: "rotom-wash"               
        }, {
            name: "rotom-fan"               
        }, {
            name: "rotom-mow"               
        }, {
            name: "castform-sunny"               
        }, {
            name: "castform-rainy"               
        }, {
            name: "basculin-blue-striped"               
        }, {
            name: "tornadus-therian"               
        }, {
            name: "meloetta-pirouette"               
        }, {
            name: "kyurem-white"               
        }, {
            name: "landorus-therian"               
        }, {
            name: "thundurus-therian"               
        }, {
            name: "kyurem-black"               
        }, {
            name: "meowstic-female"               
        }, {
            name: "pumpkaboo-large"               
        }, {
            name: "keldeo-resolute"               
        }, {
            name: "aegislash-blade"               
        }, {
            name: "pumpkaboo-small"               
        }, {
            name: "pumpkaboo-super"               
        }, {
            name: "clawitzer"               
        }, {
            name: "gourgeist-small"               
        }, {
            name: "gourgeist-large"               
        }, {
            name: "gourgeist-super"               
        }, {
            name: "venusaur-mega"               
        }, {
            name: "charizard-mega-x"               
        }, {
            name: "charizard-mega-y"               
        }, {
            name: "blastoise-mega"               
        }, {
            name: "alakazam-mega"               
        }, {
            name: "heliolisk"               
        }, {
            name: "tyrantrum"               
        }, {
            name: "dragonite"               
        }, {
            name: "kabutops"               
        }, {
            name: "swellow"               
        }, {
            name: "druddigon"               
        }, {
            name: "deoxys-normal"               
        }, {
            name: "snubbull"               
        }, {
            name: "shedinja"               
        }, {
            name: "wailord"               
        }, {
            name: "cradily"               
        }, {
            name: "combee"               
        }, {
            name: "wormadam-plant"               
        }, {
            name: "palkia"               
        }, {
            name: "fraxure"               
        }, {
            name: "skorupi"               
        }, {
            name: "tornadus-incarnate"               
        }, {
            name: "pangoro"               
        }, {
            name: "pinsir-mega"               
        }, {
            name: "aerodactyl-mega"               
        }, {
            name: "gyarados-mega"               
        }, {
            name: "bulbasaur"               
        }, {
            name: "mewtwo-mega-x"               
        }, {
            name: "heracross-mega"               
        }, {
            name: "mewtwo-mega-y"               
        }, {
            name: "ampharos-mega"               
        }, {
            name: "scizor-mega"               
        }, {
            name: "houndoom-mega"               
        }, {
            name: "banette-mega"               
        }, {
            name: "tyranitar-mega"               
        }, {
            name: "blaziken-mega"               
        }, {
            name: "gardevoir-mega"               
        }, {
            name: "mawile-mega"               
        }, {
            name: "aggron-mega"               
        }, {
            name: "medicham-mega"               
        }, {
            name: "manectric-mega"               
        }, {
            name: "absol-mega"               
        }, {
            name: "garchomp-mega"               
        }, {
            name: "lucario-mega"               
        }, {
            name: "abomasnow-mega"               
        }, {
            name: "seaking"               
        }, {
            name: "sandslash"               
        }, {
            name: "clefairy"               
        }, {
            name: "shellder"               
        }, {
            name: "alakazam"               
        }, {
            name: "steelix"               
        }, {
            name: "flaaffy"               
        }, {
            name: "tyranitar"               
        }, {
            name: "tropius"               
        }, {
            name: "shellos"               
        }, {
            name: "azelf"               
        }, {
            name: "heatran"               
        }, {
            name: "simisear"               
        }, {
            name: "krookodile"               
        }, {
            name: "leavanny"               
        }, {
            name: "ducklett"               
        }, {
            name: "dragalge"               
        }, {
            name: "barbaracle"               
        }, {
            name: "helioptile"               
        }, {
            name: "gengar-mega"               
        }, {
            name: "kangaskhan-mega"               
        }, {
            name: "charizard"               
        }, {
            name: "omastar"               
        }, {
            name: "weepinbell"               
        }, {
            name: "castform-snowy"               
        }, {
            name: "slowpoke"               
        }, {
            name: "gurdurr"               
        }, {
            name: "bibarel"               
        }, {
            name: "garbodor"               
        }, {
            name: "klinklang"               
        }, {
            name: "primeape"               
        }, {
            name: "hitmontop"               
        }, {
            name: "chatot"               
        }, {
            name: "zweilous"               
        }, {
            name: "tangrowth"               
        }, {
            name: "marowak"               
        }, {
            name: "pyroar"               
        }, {
            name: "magikarp"               
        }, {
            name: "spinarak"               
        }, {
            name: "slowking"               
        }, {
            name: "giratina-origin"               
        }, {
            name: "teddiursa"               
        }, {
            name: "zigzagoon"               
        }, {
            name: "cresselia"               
        }, {
            name: "gardevoir"               
        }, {
            name: "meditite"               
        }, {
            name: "zangoose"               
        }, {
            name: "salamence"               
        }, {
            name: "phione"               
        }, {
            name: "samurott"               
        }, {
            name: "swinub"               
        }, {
            name: "piloswine"               
        }, {
            name: "corsola"               
        }
    ];

export default pokemon;